### ISSUE TITLE
How can I donate to author?

### ISSUE THREAD

**Issue by apm40** [hyperblast/beefweb#117]
I like this component!!  It makes it much easier to control from Android devices.How can I donate?

And there's a little problem:I have many playlists(30+) and There's no way to search and select from playlists easily.Can you solve the problem?

**Comment by hyperblast** [comment]
> I like this component!! It makes it much easier to control from Android devices.How can I donate?
There is no such option at the moment, but I'll think about this ;-)

> And there's a little problem:I have many playlists(30+) and There's no way to search and select from playlists easily.Can you solve the problem?
I'll add separate issue about this, I want to redo the playlist selector eventually to become more mobile friendly etc

**Comment by hyperblast** [comment]
Added donation link
