### ISSUE TITLE
Compatibility with foo_youtube

### ISSUE THREAD

**Issue by hyperblast** [hyperblast/beefweb#121]
We should be able to add youtube URLs from `Add URL...` menu item.

**Comment by neomasterr** [comment]
Yes, can you please create an api for it? Like /player/addYoutube?url=.../watch?v=qwe123

**Comment by hyperblast** [comment]
I don't think we need special API endpoint for this. Standard [`addPlaylistItems`](https://hyperblast.org/beefweb/api/#/playlists/addPlaylistItems) endpoint should be sufficient. `foo_youtube` should register itself with foobar2000 SDK to allow other components to add youtube URLs in standard way. However since I didn't found sources for `foo_youtube` I can't really say anything about how it works actually.

**Comment by neomasterr** [comment]
Nope, plugins says error: 
{"error":{"message":"item is not under allowed path: https://www.youtube.com/watch?v=YVkUvmDQ3HY"}}


>Среда,  3 апреля 2019, 18:24 +04:00 от Hyperblast <notifications@github.com>:
>
>I don't think we need special API endpoint for this. Standard  addPlaylistItems endpoint should be sufficient. foo_youtube should register itself with foobar2000 SDK to allow other components to add youtube URLs in standard way. However since I didn't found sources for foo_youtube I can't really say anything about how it works actually.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .
Kind regards
-- 
Igor Alexandrovich

**Comment by hyperblast** [comment]
I think this is an error, it should not check URLs for file rules

**Comment by hyperblast** [comment]
Should be working now
