### ISSUE TITLE
Empty Page in mobile browsers on iPhone: Safari / FireFox

### ISSUE THREAD

**Issue by gitgetgot** [hyperblast/beefweb#127]
Hello,

on my Desktop Computers, everything works well on this browsers:
MAC:
Google Chrome Version 70.0.3538.110 (Offizieller Build) (64-Bit)
Google Chrome Version 71.0.3578.80 (Offizieller Build) (64-Bit)
WateFox 56.2.3 (64-bit)
WateFox 56.2.5 (64-bit)
Safari Version 12.0.1 (12606.2.104.1.2)

WINDOWS:
Chrome Version 68.0.3440.106 (Offizieller Build) (32-Bit)
FireFox 53.0.3 (64-bit)
WaterFox 56.2.5 (64-bit)

But on iPhone 5 with
Safari
or
FireFox 14.0 (12646)

only empty pages are seen, when opening the same link, opened in the desktop browsers.
(Same WLAN/network)

Is this working for someone out there?  ;-)

**Comment by hyperblast** [comment]
Probably some used APIs are not supported by iOS browser (Firefox on iOS uses the same engine as Safari). Unfortunately I can't test anything on iPhone because I have none.

**Comment by gitgetgot** [comment]
If there is anything I can test or debug or send you some logs or anything else, let me know.

**Comment by hyperblast** [comment]
Sorry for late response.
I think you'll also need a mac computer and some basic knowledge of web dev.
Probably I'll ask some fellow devs for help with this.
I'm not usually a web developer, this is a project for having fun with unusual areas for me.

**Comment by gitgetgot** [comment]
I own a macbookpro and basic knowledge of web dev is ok by me.

**Comment by hyperblast** [comment]
You need to setup remote debugging in Safari like [this](https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/).

Then run the development build of UI part. I could help you with this part.

Then check console for any errors.

**Comment by gitgetgot** [comment]
Late reply here too ;-/

Just want to tell that with new iPhone and new Browser version (and maybe new version of your fine component) everything works great!

It works so good, I almost forgot about this open issue :-)

Thanks for offering help end developing good software!
