### ISSUE TITLE
Window temporary flashes up on host

### ISSUE THREAD

**Issue by mrandreastoth** [hyperblast/beefweb#129]
Whenever I tap a track in the browser on my phone, a window flashes up on the host computer (Windows 10) running foobar2000. Do not expect a window to flash up, not even briefly.

**Comment by hyperblast** [comment]
Probably it's the `Adding files...` dialog, not sure if this could be disabled, I'll check.

**Comment by gitgetgot** [comment]
it looks like this:
<img width="746" alt="Bildschirmfoto 2019-07-11 um 02 29 25" src="https://user-images.githubusercontent.com/974980/61013635-c6088080-a383-11e9-80fd-423750841b86.png">

**Comment by gitgetgot** [comment]
it looks like this:
<img width="746" alt="Bildschirmfoto 2019-07-11 um 02 29 25" src="https://user-images.githubusercontent.com/974980/61013699-02d47780-a384-11e9-9d44-9ce5132a3064.png">
