### ISSUE TITLE
Show playing track name at panel.control-bar

### ISSUE THREAD

**Issue by res87th** [hyperblast/beefweb#133]
Can you add name of playing track to panel.control-bar, please?
When I open page at my mobile chrome browser I can't see name of tab,
so I don't see name of playing track.
Thank you before
![123](https://user-images.githubusercontent.com/5135411/53425640-d7697580-39fe-11e9-8581-3d6c3e4c48a6.png)

**Comment by hyperblast** [comment]
Added as separate panel, `Show playback information panel` in settings to enable.
