### ISSUE TITLE
Support rating?

### ISSUE THREAD

**Issue by hSATAC** [hyperblast/beefweb#141]
Hi, is there any chance to support rating display / setting via the API & Web GUI?

Both players has plugins for things like `%rating%` field.

Thanks for your great work! ❤️

**Comment by hyperblast** [comment]
Hello,

Regarding _reading_ rating values:

any title formatting expression could be used in the API, those are passed as-is after doing proper unescaping.

For example, in [this](https://hyperblast.org/beefweb/api/#/player/getPlayerState) and [this](https://hyperblast.org/beefweb/api/#/playlists/getPlaylistItems) endpoins `columns` mean comma-separated list of title format expressions.

I'll omit full escaping algorithm here, it's easy to figure it out from [source code](https://github.com/hyperblast/beefweb/blob/master/js/client/src/utils.js#L72).

In WebUI it's possible to configure playlist columns to use any custom title formatting (in `master`, not released yet).

I'm going to add support for now playing track title customization as well, when I have time.

Regarding _writing_ rating values:

It's not possible yet, this requires new API endpoints and implementation at plugin side.

Feel free to submit a feature request.

**Comment by hSATAC** [comment]
Thanks for your reply, well explained. Closing this for now :)
