### ISSUE TITLE
HTTP auth fails when the `Authorization` header is presented lowercase

### ISSUE THREAD

**Issue by Fusl** [hyperblast/beefweb#147]
As title says. If the HTTP basic auth header is presented as
```
authorization: Basic <base64>
```
instead of
```
Authorization: Basic <base64>
```
the authorization fails with a 401 `{"error":{"message":"Authentication required"}}`.

**Comment by hyperblast** [comment]
Thanks for nothing this.

HTTP headers should be case insensitive, but this is not implemented yet.
