### ISSUE TITLE
Rebuild on Windows fails due to path length

### ISSUE THREAD

**Issue by stengerh** [hyperblast/beefweb#150]
I had missed a prerequisite so I ran the msbuild command multiple times. On the second and further invocations it failed in the CleanServer step. The path for the generated boost HTML files ended up exceeding the Windows path length limit.

I came up with the following workarounds:
* Don't build twice a.k.a. create a fresh working copy. Good for CI/CD but not particularly practical for local development work.
* Create project directory in drive root directory, e.g. `C:\beefweb`. I don't really like spamming things into drive root directories.
* Use `subst` command to shorten paths, e.g. check out into `C:\Users\SampleUser\Projects\beefweb`, then run `subst P: C:\Users\SampleUser\Projects`, change directory to `P:\beefweb` and build from there.

Is it possible to fix the build so it can handle deleting files with long paths? I haven't found out yet if the deletion is done by msbuild itself or some other tool.

**Comment by hyperblast** [comment]
You don't really need to do a full rebuild every time.
CMake creates `.sln` file for Visual Studio which could be built as usual.
`build.proj` does full rebuild every time, which is useful for building final package, CI, etc.

**Comment by stengerh** [comment]
Thanks for the clarification! I haven't used msbuild in combination with cmake before. I am more used to build tools which support incremental builds by default. ;)

The actual reason I ran msbuild again was that I was missing the `patch` tool on the PATH. This lead to an error message when building the stringencoders library but somehow the build continued. It only failed two or three projects later which was quite confusing at first.

**Comment by hyperblast** [comment]
Server build is fully handled by CMake, client build is fully handled by Webpack. You can use those independently. MSBuild in this particular case is just a fancy shell script that builds client and server and packs artifacts together. I could use batch files or PowerShell for that, but they have their own deficiencies. Not having incremental build for this is intentional.

**Comment by hyperblast** [comment]
I've added workaround for long path names in `master` branch
