### ISSUE TITLE
Volume control via REST API?

### ISSUE THREAD

**Issue by tribbles3** [hyperblast/beefweb#191]
I can't seem to find any reference to controlling volume or mute via the REST API. Does it exist? Thanks.

**Comment by tribbles3** [comment]
Nevermind... I found it in the player-api.yml file https://github.com/hyperblast/beefweb/blob/master/docs/player-api.yml

**Comment by Barabba11** [comment]
Hi mate, I also have the same issue, I'm using Node red, how can I POST http request with desidered value? Thank you

**Comment by tribbles3** [comment]
I ended up using MQTT for volume control as I needed to control the volume of the entire audio output of the Windows PC not just foobar2000. The program I used is "IOT LINK".
