### ISSUE TITLE
beefweb dark mode? 

### ISSUE THREAD

**Issue by minimi11** [hyperblast/beefweb#206]
Hello sir, i created account just so i can ask you is there way to have dark mode pure black background? i use beefweb daily on my old phone with battery problem, so dark mode would be nice to consume less battery :) maybe you can integrate in next version in settings button to allow switch dark mode... 
Thank you for your work, beefweb is amazing for lazy people like me to not have to get out of bad to change song on foobar :D

**Comment by Dammouz** [comment]
Hello,
This point is already opened here #92 .
[@liquiddandruff](https://github.com/liquiddandruff) purposes to modify the bundle.css  file.
