### ISSUE TITLE
 evbuffer_add_file does not work in 32-bit builds

### ISSUE THREAD

**Issue by hyperblast** [hyperblast/beefweb#22]
Error:

    [warn] evbuffer_add_file: mmap(14, 0, 0) failed: Invalid argument

Similar bug in libevent: https://github.com/libevent/libevent/issues/306

Since we use this to send static files web UI is unusable until this is fixed.

**Comment by hyperblast** [comment]
Fixed

**Comment by weishian** [comment]
Hi hyperblast
how to fix please?

**Comment by weishian** [comment]
I got this bug: evbuffer_file_segment_materiallize: mmap(17, 0, 0) failed: Invaid argument
