### ISSUE TITLE
There is no way to escape commas in array query string parameters

### ISSUE THREAD

**Issue by hyperblast** [hyperblast/beefweb#93]
This is useful when requesting columns (e.g. `?plcolumns=%artist%,%title%`) that may contain commas.

**Comment by me2d13** [comment]
BTW what are possible columns names to be used in /api/playlists/p1/items? It's required parameters but I didn't find possible values in api description.
In source code I found values '%genre%','%artist%','%album%','%tracknumber%','%title%','%length%' in api test which seems to work, are there any ohers? E.g. file name + path?

**Comment by me2d13** [comment]
Found it in the meantime. Column names probably come from foobar so are mentioned here https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference
